vich_uploader:
    db_driver: orm
    metadata:
        type: attribute


    mappings:
        product:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public/images/product'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true